# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - run: echo '//npm.pkg.github.com/:_authToken=${COCUNAT_GITHUB_TOKEN}' > .npmrc
      - run: echo '@cocunat:registry=https://npm.pkg.github.com' >> .npmrc
      - run: echo '@cocunat:always-auth=true' >> .npmrc
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm install npm-cli-login
      - run: node_modules/npm-cli-login/bin/npm-cli-login.js -u itcocunat -p ${{ secrets.COCUNAT_GITHUB_TOKEN }} -e it@cocunat.com -r https://npm.pkg.github.com
      - run: npm publish --registry=https://npm.pkg.github.com --scope=cocunat
        env:
          GITHUB_TOKEN: ${{ secrets.COCUNAT_GITHUB_TOKEN }}